<?php
   if(isset($_SESSION['video_savesettings']))
      {
      if($_SESSION['video_savesettings'] == 1)
         {
         ?><div class="result success"><?=CVideo::GetTranslate('b_settings_save_success')?></div><?php
         }
      else
         {
         ?><div class="result error"><?=CVideo::GetTranslate('b_settings_save_error')?></div><?php
         }
      }
   ?>

<div class="main">
    <div class="description">
    <h1 class="title"><?=CVideo::GetTranslate('main_title')?></h1>
    </div>
    
    <div class="form">
    <form action="" method="post" id="mainForm" enctype="multipart/form-data" name="parse_text">
        <div class="left" style="margin-right: 50px;">
            <!-- ВЫБОР КЕЙВОРДОВ -->
            <div class="box">
                <div class="name">
                   <?=CVideo::GetTranslate('b_keywords')?>
                   <?=CModel_helper::SwapLinks('keysFrom', $this->GetSettings()->Get('keysFrom', 'list'), 'swapKeysFrom', array('file'=>CHome::GetTranslate('from_file'), 'list'=>CHome::GetTranslate('from_list'))) ?>
                </div>
                <input type="file" name="keysFromFile" id="keysFromFile" size="25"
                       style="display: <?=$this->GetSettings()->Get('keysFrom', 'list') != 'list' ? 'block' : 'none' ?>;">
                <select name="keysFromList" id="keysFromList"
                        style="width: 242px; display: <?=$this->GetSettings()->Get('keysFrom', 'list') == 'list' ? 'block' : 'none' ?>;">
                   <?=CModel_helper::ListFiles(CModel_keywords::PATH_KEYWORDS, $this->GetSettings()->Get('keysFromList'))?>
                </select>
            </div>
            <div class="box">
                <i><?=CVideo::GetTranslate('b_name')?>:</i>
                <input name="filename" id="filename" style="width: 238px;" value=""
                       placeholder="mytext.txt">
            </div>
            
        </div>
            
        <div class="left">
<?
$threads = $this->GetSettings()->Get('threads');
$proxies = $this->GetGlobalSettings()->GetProxies();
$socks_proxies = $this->GetGlobalSettings()->GetSocksProxies();
$disabled_threads = false;
if(empty($proxies) && empty($socks_proxies))
{
$threads = "";
$disabled_threads = true;
}
?>                
            
            <div class="box">
                <input type="checkbox"
                       name="threads" <?=$threads == 'on' ? "checked='checked'" : NULL ?>
                       onclick='swapMaxThreads(this);'
                       id="threads" class="cb"<?=$disabled_threads?' disabled="disabled"':''?> disabled="disabled">
                <label for="threads"><?=CVideo::GetTranslate('b_threads')?></label>
                    <div id="count_threads" style="display:<?=($threads == 'on')?'block':'none'?>">
                       <?=CImage::GetTranslate('b_count_threads')?>
                     <input type="text" name="threads_count" id="threads_count" style="width: 40px;" value="<?=$this->GetSettings()->Get('threads_count',15)?>" title="<?=CImage::GetTranslate('b_threads_count_title')?>">
                    </div>

            </div>        

                <div class="box">
                    <?=CVideo::GetTranslate('b_pause')?>
                    <input type="text" name="pause" id="pause" style="width: 40px;" value="<?=$this->GetSettings()->Get('pause',2)?>"> 
                </div>
                <div class="box">
                    <?=CVideo::GetTranslate('b_count_video')?>: 
                    <input type="text" name="count_video" id="count_video" style="width: 40px;" value="<?=$this->GetSettings()->Get('count_images',300)?>"> 
                </div>



        </div>
        
        <div class="clear"></div>

        <input type="submit" value="<?=CVideo::GetTranslate('b_add_task')?>" class="simpleButton" name="a[savetask]">

    </form>
    </div>
    
    <div class="clear"></div>
</div>


<div class="content">
    <div style="margin: 0 0 10px 0; position: relative;">
       <?php if(!empty($this->m_list_task))
       {
       ?>
          <?php if($this->m_model->IsStartTask())
          { ?>

              <form action="?module=video&a[stoptask]" method="post" style="margin-bottom: 20px;">
                 <?=CVideo::GetTranslate('b_working')?>
                  <input type="submit" value="<?=CVideo::GetTranslate('b_stop')?>" class="simpleButton"
                         style=" vertical-align: middle;">

                  <a href="?module=video" style="margin-left: 10px;"><?=CVideo::GetTranslate('b_refresh')?></a>
              </form>
             <?php }
       else
          { ?>
          <form action="?module=video&a[runtasks]" method="post" style="margin-bottom: 20px;">
              <input type="submit" value="<?=CVideo::GetTranslate('b_task_start')?>" class="simpleButton"
                     style="vertical-align: middle;">

              <a href="?module=video&a[cleartask]"
                 onclick="return confirm(<?=CVideo::GetTranslate('b_are_sure_delete')?>)" style="margin-left: 10px;"
                 class="dashed"><?=CVideo::GetTranslate('b_task_delete')?></a>
          </form><?php 
          } ?>
          
          <form action="?module=video" method="post" name="form_texts" style="margin-bottom: 5px;">
               <input type="submit" name="a[deletevideo]" value="<?=CVideo::GetTranslate('b_delete_texts')?>">
               <input type="submit" name="a[repeatvideo]" value="<?=CVideo::GetTranslate('b_repeat_texts')?>">
               <input type="hidden" name="video_ids" value="" id="video_ids">
           </form>
           
    <form action="?module=tasks" method="post" name="texts_need">
           <table class="table" cellpadding="5" cellspacing="0" border="0">
               <tr>
                   <th style="width:16px;"><input type="checkbox"
                                                  onclick="CheckedCheckbox(document.texts_need,'video_',this.checked,'video_ids')"/>
                   </th>
                   <th><?=CVideo::GetTranslate('b_keywords')?></th>
                   <th><?=CVideo::GetTranslate('b_path_download')?></th>
                   <th style="width: 118px;"><?=CVideo::GetTranslate('b_date')?></th>
                   <th style="width: 100px;"><?=CVideo::GetTranslate('b_status')?></th>
               </tr>

              <?php
             $c = 0;
              foreach($this->m_list_task as $fname)
                 {
                 $info=$this->m_model->GetTask($fname);
                   $c++;
                 $system='';
                 ?>
                     <tr>
                         <td><input type="checkbox" name="video[]" value="<?=$info['number']?>" id="video_<?=$info['number']?>"
                                    onclick="UpdateCheckedCheckbox('video_ids',this.checked,this.value)"/></td>
                         <td><?=$info['task']['keysFrom'] == 'list' ? $info['task']['keysFromList'] : count($info['task']['keywords']) . ' keywords' ?></td>
                         <td><?=$info['task']['filename']?></td>
                         <td><?=date("d.m.Y H:i", $info['date_create'])?></td>
                         <td><?=CModel_task::GetStatusName($info['status'])?></td>
                     </tr><?
                 }?>
           </table>
       <?= CVideo::GetTranslate('b_total') ?>: <?= $c ?>
          <?
       }?>
    </div>
</div>





