<? global $TRANSLATE; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico">
    <link href="styles/styles.css" type="text/css" rel="stylesheet">
    <title>redButton &mdash; License error</title>
</head>
<body>
<h1><?=$TRANSLATE[$LNG]['page_license_error']?></h1>

<p><?=$TRANSLATE[$LNG]['page_license_error_text']?></p>

<div style="border-top: 1px solid #DFDCD1; padding: 15px 0 0 0; margin: 10px 0 0 0; color: #8F8D86;">
    &hearts; <?=$TRANSLATE[$LNG]['bottom_page']?>
</div>
</body>
</html>