   <?php
   if(isset($_SESSION['texts_savesettings']))
      {
      if($_SESSION['texts_savesettings'] == 1)
         {
         ?><div class="result success"><?=CTexts::GetTranslate('b_settings_save_success')?></div><?php
         }
      else
         {
         ?><div class="result error"><?=CTexts::GetTranslate('b_settings_save_error')?></div><?php
         }
      }
   ?>

<div class="main">
    <div class="description">
    <h1 class="title"><?=CTexts::GetTranslate('main_title')?></h1>
    </div>
    
    <div class="form">
    <form action="" method="post" id="mainForm" enctype="multipart/form-data" name="parse_text">
        <div class="left" style="margin-right: 50px;">
            <!-- ВЫБОР КЕЙВОРДОВ -->
            <div class="box">
                <div class="name">
                   <?=CTexts::GetTranslate('b_keywords')?>
                   <?=CModel_helper::SwapLinks('keysFrom', $this->GetSettings()->Get('keysFrom', 'list'), 'swapKeysFrom', array('file'=>CHome::GetTranslate('from_file'), 'list'=>CHome::GetTranslate('from_list'))) ?>
                </div>
                <input type="file" name="keysFromFile" id="keysFromFile" size="25"
                       style="display: <?=$this->GetSettings()->Get('keysFrom', 'list') != 'list' ? 'block' : 'none' ?>;">
                <select name="keysFromList" id="keysFromList"
                        style="width: 242px; display: <?=$this->GetSettings()->Get('keysFrom', 'list') == 'list' ? 'block' : 'none' ?>;">
                   <?=CModel_helper::ListFiles(CModel_keywords::PATH_KEYWORDS, $this->GetSettings()->Get('keysFromList'))?>
                </select>
            </div>
            <div class="box">
                <i><?=CTexts::GetTranslate('b_name')?>:</i>
                <input name="filename" id="filename" style="width: 238px;" value=""
                       placeholder="mytext.txt">
            </div>
            <div class="box">
                <i><?=CTexts::GetTranslate('b_language')?>:</i>
                <select name="language" id="language" style="width: 100px;">
                   <?php
                   foreach(CTranslate::GetLanguages() as $lang)
                      {
                      ?>
                          <option value="<?=$lang?>"<?=$lang == $this->m_lang ? " selected='selected'" : ""?>><?=$lang?></option>
                         <?php
                      }
                   ?>
                </select>
            </div>        
            
            
        </div>
            
        <div class="left">
            <div class="box">
                <input type="checkbox"
                       name="google" <?=$this->GetSettings()->Get('google') == 'on' ? "checked='checked'" : NULL ?>
                       id="google" class="cb">
                <label for="google"><?=CTexts::GetTranslate('b_google')?></label><br>

                <input type="checkbox"
                       name="yandex" <?=$this->GetSettings()->Get('yandex') == 'on' ? "checked='checked'" : NULL ?>
                       id="yandex" class="cb">
                <label for="yandex"><?=CTexts::GetTranslate('b_yandex')?></label>
            </div>
<?
$threads = $this->GetSettings()->Get('threads');
$proxies = $this->GetGlobalSettings()->GetProxies();
$socks_proxies = $this->GetGlobalSettings()->GetSocksProxies();
$disabled_threads = false;
if(empty($proxies) && empty($socks_proxies))
{
//$threads = "";
//$disabled_threads = true;
}
?>                
            
            <div class="box">
                <input type="checkbox"
                       name="threads" <?=$threads == 'on' ? "checked='checked'" : NULL ?>
                       onclick='swapMaxThreads(this);'
                       id="threads" class="cb">
                <label for="threads"><?=CTexts::GetTranslate('b_threads')?></label>
                    <div id="count_threads">
                       <?=CImage::GetTranslate('b_count_threads')?>
                     <input type="text" name="threads_count" id="threads_count" style="width: 40px;" value="<?=$this->GetSettings()->Get('threads_count',15)?>" title="<?=CImage::GetTranslate('b_threads_count_title')?>">
                    </div>

            </div>        

            <div class="box">
                <input type="checkbox"
                       name="check_dublicate" <?=$this->GetSettings()->Get('check_dublicate') == 'on' ? "checked='checked'" : NULL ?> 
                       id="check_dublicate" class="cb">
                <label for="check_dublicate"><?=CTexts::GetTranslate('b_check_dublicate')?></label>
            </div>        
            <div class="box">
                <input type="text" name="min_symbols" id="min_symbols" style="width: 40px;text-align:right;" value="<?=$this->GetSettings()->Get('min_symbols',300)?>">
                <?=CTexts::GetTranslate('b_min_symbols')?>
            </div>
                <div class="box">
                    <?=CImage::GetTranslate('b_pause')?>
                    <input type="text" name="pause" id="pause" style="width: 40px;" value="<?=$this->GetSettings()->Get('pause',4)?>"> 
                </div>


        </div>
        
        <div class="clear"></div>

        <input type="submit" value="<?=CTexts::GetTranslate('b_add_task')?>" class="simpleButton" name="a[savetask]">

    </form>
    </div>
    
    <div class="clear"></div>
</div>


<div class="content">
    <div style="margin: 0 0 10px 0; position: relative;">
       <?php if(!empty($this->m_list_task))
       {
       ?>
          <?php if($this->m_model->IsStartTask())
          { ?>

              <form action="?module=texts&a[stoptask]" method="post" style="margin-bottom: 20px;">
                 <?=CTexts::GetTranslate('b_working')?>
                  <input type="submit" value="<?=CTexts::GetTranslate('b_stop')?>" class="simpleButton"
                         style=" vertical-align: middle;">

                  <a href="?module=texts" style="margin-left: 10px;"><?=CTexts::GetTranslate('b_refresh')?></a>
              </form>
             <?php }
       else
          { ?>
          <form action="?module=texts&a[runtasks]" method="post" style="margin-bottom: 20px;">
              <input type="submit" value="<?=CTexts::GetTranslate('b_task_start')?>" class="simpleButton"
                     style="vertical-align: middle;">

              <a href="?module=texts&a[cleartask]"
                 onclick="return confirm(<?=CTexts::GetTranslate('b_are_sure_delete')?>)" style="margin-left: 10px;"
                 class="dashed"><?=CTexts::GetTranslate('b_task_delete')?></a>
          </form><?php 
          } ?>
          
          <form action="?module=texts" method="post" name="form_texts" style="margin-bottom: 5px;">
               <input type="submit" name="a[deletetexts]" value="<?=CTexts::GetTranslate('b_delete_texts')?>">
               <input type="submit" name="a[repeattexts]" value="<?=CTexts::GetTranslate('b_repeat_texts')?>">
               <input type="hidden" name="texts_ids" value="" id="texts_ids">
           </form>
           
    <form action="?module=tasks" method="post" name="texts_need">
           <table class="table" cellpadding="5" cellspacing="0" border="0">
               <tr>
                   <th style="width:16px;"><input type="checkbox"
                                                  onclick="CheckedCheckbox(document.texts_need,'texts_',this.checked,'texts_ids')"/>
                   </th>
                   <th style="width: 105px;"><?=CTexts::GetTranslate('b_system')?></th>
                   <th><?=CTexts::GetTranslate('b_keywords')?></th>
                   <th style="width: 80px;"><?=CTexts::GetTranslate('b_language')?></th>
                   <th><?=CTexts::GetTranslate('b_path_download')?></th>
                   <th style="width: 118px;"><?=CTexts::GetTranslate('b_date')?></th>
                   <th style="width: 100px;"><?=CTexts::GetTranslate('b_status')?></th>
               </tr>

              <?php
             $c = 0;
              foreach($this->m_list_task as $fname)
                 {
                 $info=$this->m_model->GetTask($fname);
                   $c++;
                 $system='';
                 if(!empty($info['task']['google'])) $system.=(!empty($system) ? ", " : "") . 'google';
                 if(!empty($info['task']['yandex'])) $system.=(!empty($system) ? ", " : "") . 'yandex';
                 ?>
                     <tr>
                         <td><input type="checkbox" name="texts[]" value="<?=$info['number']?>" id="texts_<?=$info['number']?>"
                                    onclick="UpdateCheckedCheckbox('texts_ids',this.checked,this.value)"/></td>
                         <td><?=$system?></td>
                         <td><?=$info['task']['keysFrom'] == 'list' ? $info['task']['keysFromList'] : count($info['task']['keywords']) . ' keywords' ?></td>
                         <td><?=$info['task']['language']?></td>
                         <td><?=$info['task']['filename']?></td>
                         <td><?=date("d.m.Y H:i", $info['date_create'])?></td>
                         <td><?=CModel_task::GetStatusName($info['status'])?></td>
                     </tr><?
                 }?>
           </table>
       <?= CTexts::GetTranslate('b_total') ?>: <?= $c ?>
          <?
       }?>
    </div>
</div>





