<?php
$TRANSLATE = array('ru' => array('enter_password'                   => 'Введите пароль',
                                 'make_password'                    => 'Придумайте пароль',
                                 'enter'                            => 'Войти',
                                 'exit'                             => 'Выйти',
                                 'bottom_page'                      => 'Генератор дорвеев redButton 3',
                                 'page_not_found'                   => 'Страница не найдена',
                                 'download_last_version'            => 'Скачать последнюю версию',
                                 'page_license_error'               => 'Ошибка с лицензией',
                                 'page_license_error_text'          => 'Возможно проблема c лицензией, пожалуйста, обратитесь в техподдержку на сайте <a href="http://support.getredbutton.com">support.getredbutton.com</a> или на e-mail <a href="maito:support@getredbutton.com">support@getredbutton.com</a>',
                                 'page_license_activate_error'      => 'Ошибка с активационной лицензией',
                                 'page_license_activate_error_text' => 'Возможно проблема c лицензией, пожалуйста, обратитесь в техподдержку на сайте <a href="http://support.getredbutton.com">support.getredbutton.com</a> или на e-mail <a href="maito:support@getredbutton.com">support@getredbutton.com</a>',
                                 'new_version'                      => 'Скачать новую версию ',
                                 'wait_status'                      => 'в ожидании',
                                 'starting_status'                  => 'выполняется',
                                 'finish_status'                    => 'завершено',
                                 'finish_failed_status'             => 'завершено с ошибками',
                                 'error_status'                     => 'ошибка',
                                 'site_techsupport'                 => 'Тех поддержка: support.getredbutton.com',
                                 'php_version'                      => 'Версия PHP меньше 5.2.0',
                                 'php_allow_url_fopen'              => 'Устнановите в php.ini параметру allow_url_fopen значение on',
                                 'php_mbstring'                     => 'Модуль mbstring не установлен',
                                 'php_curl'                         => 'Модуль curl не установлен',
                                 'php_data_write'                   => 'Нет прав на запись в папку data',
                                 'php_links_write'                  => 'Нет прав на запись в папку data/links',
                                 'php_images_write'                 => 'Нет прав на запись в папку data/images',
                                 'php_settings_write'               => 'Нет прав на запись в папку data/settings',
                                 'php_tasks_write'                  => 'Нет прав на запись в папку data/tasks',
                                 'php_licenses_write'               => 'Нет прав на запись в папку data/licenses',),
                   'en' => array('enter_password'                   => 'Enter password',
                                 'make_password'                    => 'Make up new password',
                                 'enter'                            => 'Enter',
                                 'exit'                             => 'Exit',
                                 'bottom_page'                      => 'Doorways generator redButton 3',
                                 'page_not_found'                   => 'Page not found',
                                 'download_last_version'            => 'Download last version',
                                 'page_license_error'               => 'License failed',
                                 'page_license_error_text'          => 'Please, write to support website <a href="http://support.getredbutton.com">support.getredbutton.com</a> or email <a href="maito:support@getredbutton.com">support@getredbutton.com</a>',
                                 'page_license_activate_error'      => 'Activate License failed',
                                 'page_license_activate_error_text' => 'Please, write to support website <a href="http://support.getredbutton.com">support.getredbutton.com</a> or email <a href="maito:support@getredbutton.com">support@getredbutton.com</a>',
                                 'new_version'                      => 'Download new version ',
                                 'wait_status'                      => 'waiting',
                                 'starting_status'                  => 'beginning',
                                 'finish_status'                    => 'finished',
                                 'finish_failed_status'             => 'finished with errors',
                                 'error_status'                     => 'error',
                                 'site_techsupport'                 => 'Tech support: support.getredbutton.com',
                                 'php_version'                      => 'Весрия PHP меньше 5.2.0',
                                 'php_allow_url_fopen'              => 'php.ini has allow_url_fopen set to on',
                                 'php_mbstring'                     => 'Module mbstring does not install',
                                 'php_curl'                         => 'Module curl does not install',
                                 'php_data_write'                   => 'Access denied to path data',
                                 'php_links_write'                  => 'Access denied to path data/links',
                                 'php_images_write'                 => 'Access denied to path data/images',
                                 'php_settings_write'               => 'Access denied to path data/settings',
                                 'php_tasks_write'                  => 'Access denied to path data/tasks',
                                 'php_licenses_write'               => 'Access denied to path data/licenses',),)
?>